theme = "hugo-now-ui"
baseURL = ""
languageCode = "nl-BE"
title = "Duikcentrum Dolphin Buddys"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir = "./docs"
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Education"
    url = "/Opleidingen/"
    weight = 2


[[menu.main]]
    name = "Experience"
    url = "/ervaringen/"
    weight = 2

[[menu.main]]
    name = "Equipment"
    url = "/materiaal/"
    weight = 4

[[menu.main]]
    name = "Environment"
    url = "/onderwaterwereld/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6


[[menu.main]]
    name = "https://www.facebook.com/dolphinbuddys/"
    pre = '<i class="fa fa-facebook-square" data-toggle="tooltip" data-placement="bottom" data-content="Facebook"></i>'
    weight = 7

[[menu.main]]
    name = "https://www.instagram.com/dolphin.buddys/"
    pre = '<i class="fa fa-instagram" data-toggle="tooltip" data-placement="bottom" data-content="Instagram"></i>'
    weight = 8

[[menu.main]]
name = "https://www.youtube.com/@duikcentrumdolphinbuddys9386"
pre = '<i class="fa fa-youtube" data-toggle="tooltip" data-placement="bottom" data-content="YouTube"></i>'
weight = 9

[[menu.main]]
    name = "https://www.padi.com/dive-center/belgium/duikcentrum-dolphin-buddys/"
    pre = '<div class="padilogo"></div>'
    weight = 10

[[menu.footer]]
    identifier = "facebook"
    pre = "<i class='fa fa-facebook-square'></i>"
    url = "https://www.facebook.com/dolphinbuddys/"

[[menu.footer]]
    identifier = "instagram"
    url = "https://www.instagram.com/dolphin.buddys/"
    pre = '<i class="fa fa-instagram"></i>'

[params]
    background = "/img/header.jpg"
    tint = "orange"
    custom_css = []
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "Duikcentrum Dolphin Buddys"



    

