theme = "hugo-now-ui"
baseurl = ""
languageCode = "nl-BE"
title = "Duikcentrum Dolphin Buddys"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir = "./docs"
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Duikclub"
    url = "/ervaringen/duikclub"
    parent = "Ervaringen"
    weight = 1

[[menu.main]]
    name = "Jeugdwerking"
    url = "/ervaringen/jeugdwerking"
    parent = "Ervaringen"
    weight = 2

[[menu.main]]
    name = "Duiken met een beperking"
    url = "/ervaringen/beperking"
    parent = "Ervaringen"
    weight = 3

[[menu.main]]
    name = "Activiteiten"
    url = "/ervaringen/activiteiten"
    parent = "Ervaringen"
    weight = 4

[[menu.main]]
    name = "Noordzeeduiken"
    url = "/ervaringen/noordzeeduiken"
    parent = "Ervaringen"
    weight = 5

[[menu.main]]
    name = "Opleidingen"
    url = "/opleidingen/"
    weight = 2

[[menu.main]]
    name = "Ervaringen"
    url = "/ervaringen/"
    weight = 3

[[menu.main]]
    name = "Materiaal"
    url = "/materiaal/"
    weight = 4

[[menu.main]]
    name = "Milieu"
    url = "/milieu/"
    weight = 5

[[menu.main]]
    name = "Initiaties"
    url = "/initiaties/"
    weight = 6

[[menu.main]]
    name = "Veiligheid"
    url = "/veiligheid/"
    weight = 7

[[menu.main]]
    name = "Over Ons"
    url = "/overons/"
    identifier="overons"
    weight = 8

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 9


[[menu.main]]
    name = "https://www.facebook.com/dolphinbuddys/"
    pre = '<i class="fa fa-facebook-square" data-toggle="tooltip" data-placement="bottom" data-content="Like ons op Facebook"></i>'
    weight = 10

[[menu.main]]
    name = "https://www.instagram.com/dolphin.buddys/"
    pre = '<i class="fa fa-instagram" data-toggle="tooltip" data-placement="bottom" data-content="Volg ons op Instagram"></i>'
    weight = 11

[[menu.main]]
    name = "https://www.padi.com"
    pre = '<div class="padilogo"></div>'
    weight = 12

[[menu.footer]]
    identifier = "facebook"
    pre = "<i class='fa fa-facebook-square'></i>"
    url = "https://www.facebook.com/dolphinbuddys/"

[[menu.footer]]
    identifier = "instagram"
    url = "https://www.instagram.com/dolphin.buddys/"
    pre = '<i class="fa fa-instagram"></i>'

[params]
    background = "/img/bg11.jpg"
    tint = "orange"
    custom_css = []
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "Duikcentrum Dolphin Buddys"



    

