theme = "hugo-now-ui"
baseurl = "dolphin-buddys"
languageCode = "en-us"
title = "Dolphin Buddys"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "./docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "Het Duikcentrum"
    url = "/overons/#centrum"
    parent = "overons"
[[menu.main]]
    name = "Ons Team"
    url = "/overons/#team"
    parent = "overons"

[[menu.main]]
    name = "Opleidingen"
    url = "/opleidingen/"
    
    weight = 2
[[menu.main]]
    name = "Ervaringen"
    url = "/ervaringen/"
    
    weight = 3
[[menu.main]]
    name = "Materiaal"
    url = "/materiaal/"
    weight = 4

#[[menu.main]]
#    name = "Initiaties"
#    url = "/initiaties/"
#    weight = 5

[[menu.main]]
    name = "Milieu"
    url = "/milieu/"
    weight = 6

#[[menu.main]]
#    name = "Veiligheid"
#    url = "/veiligheid/"
#    weight = 7

[[menu.main]]
    name = "Over Ons"
    url = "/overons/"
    identifier="overons"
    weight = 8

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 9


[[menu.main]]
    name = ""
    url = "https://www.facebook.com/dolphinbuddys/"
    pre = '<i class="fa fa-facebook-square" data-toggle="tooltip" data-placement="bottom" data-content="Like ons op Facebook"></i>'
    weight = 10

[[menu.footer]]
    identifier = "facebook"
    pre = "<i class='fa fa-facebook-square'></i>"
    url = "https://www.facebook.com/dolphinbuddys/"

[params]
    background = "/img/bg11.jpg"
    tint = "orange"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "Duikcentrum Dolphin Buddys"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


    

